application: cm-kang
version: 14
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /rss
  script: diff.py

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /apple-touch-icon\.png
  static_files: apple-touch-icon.png
  upload: apple-touch-icon\.png
  
- url: /google(.*?)\.html
  static_files: google\1.html
  upload: google(.*?)\.html
  
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  
- url: /.*
  script: diff.py